dialect = "postgresql"
host = "db.wcwiozumyufdtskudlvi.supabase.co"
port = "5432"
database = "estoque"
username = "postgres"
password = "Amoracolorida1!"

[connections.supabase]
SUPABASE_URL = "https://mwvjsdxbnraqjamjdtqy.supabase.co"  # Substitua pelo seu URL do Supabase
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dmpzZHhibnJhcWphbWpkdHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzM3MjYsImV4cCI6MjA2NTMwOTcyNn0.y2JkLAWU3u6bwTvY8jbjQSH0cnohwffkC7ER5YHMaFg"  # Substitua pela sua chave de API do Supabase
